### ISSUE TITLE
Typed navigation parameters?

### ISSUE THREAD

**Issue by johankson** [TinyStuff/TinyNavigationHelper#10]
This is a bit of a long shot, but could we create typed navigation parameters?

```csharp
// Definition
Task NavigateToAsync<TView, TArgument>(TView view, TArgument argument);

// Usage (argument is deferred by usage)
await Navigation.NavigateToAsync<ListEditorView>(shoppingList);
```

This means the view model must accept a specific set of parameters using generics as well.

```csharp
public class MyViewModel<ShoppingList> : ViewModelBase<TArgument>
{
    public async override Task Initialize()
    {
         var parameter = NavigationParameter; // of the type ShoppingList (null or set to a reference of an object)
    }
}
```

PROS:
* Type safety

CONS:
* Might be hard to implement cleanly

**Comment by dhindrik** [comment]
I like this idea.

**Comment by dhindrik** [comment]
Do you really need to make the Navigate Metod generic? I think it will work to have it as object and only maker the viewmodel generic.

**Comment by johankson** [comment]
Yes we do :)
It will make it more type safe... You can always use <object> if you want to send an object.
We will remove the <TView> generic parameter though.

**Comment by dhindrik** [comment]
If this still is interesting, please open a new issue for TinyMvvm.
