### ISSUE TITLE
Unable to navigate from a Modal page

### ISSUE THREAD

**Issue by jonatansoderberg** [TinyStuff/TinyNavigationHelper#14]
In NavigateToAsync, when private field _modalNavigationPage is not null, the execution end up in an empty else-block instead of navigating to the requested page.

This happends if we first open a modal:

NavigationHelper.Current.OpenModalAsync("SomeView", withNavigation: true);

And then try to navigate from "SomeView" to "SomeView2"

NavigationHelper.Current.NavigateToAsync("SomeView2");

**Comment by dhindrik** [comment]
This is released in 1.3.7. Will be on NuGet as far as they have updated their indexes.
