### ISSUE TITLE
ViewModel Navigation for All Platforms 

### ISSUE THREAD

**Issue by techierathore** [TinyStuff/TinyNavigationHelper#15]
Hey guys needed Some help with Tiny Navigation library . I need to use the same in an application which has to support multiple platforms like Xamarin.Mac and Windows WPF apart from regular iOS, Android and UWP . Do you have a sample where you have done ViewModel Navigation targeting all these frameworks alongwith the Xamarin.Forms project.

**Comment by dhindrik** [comment]
This is now a part of TinyMvvm.
