### ISSUE TITLE
NavigateTo<T>

### ISSUE THREAD

**Issue by johankson** [TinyStuff/TinyNavigationHelper#4]
Can we add support for navigating to a type directly. Most of the time you only register one view of a specific type.

```csharp
NavigationHelper.NavigateTo<AboutView>();
```

**Comment by johankson** [comment]
Is this a good thing? I really would like to get rid of magic strings in the code base

```csharp
// I don't like this
await Navigation.NavigateToAsync("ListEditorView", shoppingList);

// This could do the same thing, we simply take the name of the view from the type
await Navigation.NavigateToAsync<ListEditorView>(shoppingList);
```

PROS:
* It will be more typesafe

CONS:
* Namespace issues?

**Comment by johankson** [comment]
Suggested by @dhindrik to add this feature as an extension method

**Comment by dhindrik** [comment]
You can also use nameof:
```csharp
await Navigation.NavigateToAsync(nameof(ListEditorView));
```

**Comment by dhindrik** [comment]
I approved this, while there are already extensions for navigation to specific instance of an view.

**Comment by dhindrik** [comment]
But I don't recommend to use those methods if you use it inside an ViewModel. It will make it harder to extend your application to non Xamarin.Forms platforms. If you use nameof() you can still use it with other platforms, if you name the views the same.
