### ISSUE TITLE
There is no error message or notification if navigating to an unknown view

### ISSUE THREAD

**Issue by johankson** [TinyStuff/TinyNavigationHelper#9]
When calling

```csharp
await Navigation.NavigateToAsync("UnknownView", parameter);
```

there is no notification of any kind if the view doesn't exist?

**Comment by dhindrik** [comment]
You using it inside of TinyMvvm? I guess this bug require fixes in the both DefaultViewCreator of TinyNavigation and the TinyMvvm view creator.

**Comment by dhindrik** [comment]
Fixed, will be included in the next release.
